### PR TITLE
NVHPC@21.11+ workaround for Random123.

### PR DESCRIPTION
**Pull request by olupton**
**Description**
Mainly add a workaround for an issue in Random123 compiler detection logic with versions 21.11 and newer of the NVHPC compilers.

- Add `-DR123_USE_INTRIN_H=0` in NVHPC builds with GPU support disabled to avoid #724, as recommended in https://github.com/DEShawResearch/random123/issues/6.
- If GPU support is enabled we compile with `-cuda`, which means Random123 treats `nvc++` as `nvcc` and we do not see the issue.
- Fix some compiler warnings when compiling with NVHPC and GPU support disabled.

Closes https://github.com/BlueBrain/CoreNeuron/issues/724.
See also: https://github.com/neuronsimulator/nrn/pull/1587.

**How to test this?**
Build with NVHPC 21.11 or newer and GPU support disabled. Without this PR, you should see compilation errors.

**Use certain branches for the SimulationStack CI**

CI_BRANCHES:NEURON_BRANCH=master,

### CODE REVIEW

**Review by pramodk — APPROVED** [review]
LGTM

File: CMakeLists.txt [hunk 1]
```diff
@@ -238,7 +238,15 @@ endif()
...
+  list(APPEND CORENRN_COMPILE_DEFS EIGEN_DONT_VECTORIZE=1)
+  if(NOT CORENRN_ENABLE_GPU AND ${CMAKE_CXX_COMPILER_VERSION} VERSION_GREATER_EQUAL 21.11)
+    # Random123 does not play nicely with NVHPC 21.11+'s detection of ABM features if it detects the
+    # compiler to be PGI or NVHPC, see: https://github.com/BlueBrain/CoreNeuron/issues/724 and
+    # https://github.com/DEShawResearch/random123/issues/6. In fact in GPU builds Random123
+    # (mis)detects nvc++ as nvcc because we pass the -cuda option and we therefore avoid the
+    # problem. If GPU support is disabled, we define R123_USE_INTRIN_H=0 to avoid the problem.
+    list(APPEND CORENRN_COMPILE_DEFS R123_USE_INTRIN_H=0)
+  endif()
 endif()
```
Comment (pramodk) [inline CMakeLists.txt:250]: @olupton : FYI - (accidentally) I was trying to use cpu wheel with nvhpc compiler and end-up with this error. 

Wonder if this logic needs to be pushed at later stage (in `nrnivmodl_core_makefile` or similar)
